animations {
  enabled = true

  bezier = bounce, 0.5, 1.5, 0.5, -0.5
  bezier = jump, 1, 0, 0, 0
  bezier = linear, 0, 0, 1, 1

  #       NAME,      ONOFF, SPEED, CURVE,    [STYLE]
  animation = global,        1, 2.5, jump
  animation = border,        1, 2.5, linear
  animation = windows,       1, 2.5, jump
  animation = windowsIn,     0, 2.5, jump
  animation = windowsOut,    0, 2.5, jump
  animation = fadeIn,        1, 2.5, jump
  animation = fadeOut,       1, 2.5, jump
  animation = fade,          1, 2.5, jump
  animation = layers,        1, 2.5, linear
  animation = layersIn,      0, 2.5, jump
  animation = layersOut,     0, 2.5, linear
  animation = fadeLayersIn,  1, 2.5, jump
  animation = fadeLayersOut, 1, 2.5, jump
  animation = workspaces,    1, 2.5, jump
  animation = workspacesIn,  1, 2.5, jump
  animation = workspacesOut, 1, 2.5, jump
  animation = zoomFactor,    1, 2.5, jump
}
