# Terminal with Fancy Cursor
$terminal = kitty

# Terminal File Manager
$fileManager = kitty yazi

# App Launcher
$appLauncher = rofi -show drun

# Cool Firefox Fork
$browser = zen-browser

# Nice Terminal System Monitor
$sysMonitor = kitty btop
