# terminal with fancy cursor
$terminal = kitty

# terminal file manager
$file_manager = kitty yazi

# app launcher
$application_launcher = rofi -show drun

# cool firefox fork
$browser = zen-browser

# nice terminal system monitor
$system_monitor = kitty btop

# gtk image viewer
$image_viewer = gthumb

# gtk raster editor
$raster_editor = gimp

# gtk vector editor
$vector_editor = inkscape
