#Run Applications 
bind = SUPER, T, exec, $terminal
bind = SUPER, E, exec, [float; size 960 540] $fileManager
bind = SUPER, A, exec, $menu
bind = SUPER, B, exec, $browser
bind = CONTROL SHIFT, ESCAPE, exec, [float; size 960 540; move 480 4] $sysMonitor

bind = SUPER, Q, killactive,
bind = SUPER, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = SUPER, F, togglefloating,

#Reload Configs
bind = SUPER, R, exec, hyprctl reload 
bind = SUPER, R, exec, swaync-client -R && swaync-client -rs 
bind = SUPER, R, exec, pkill waybar && waybar &

#Color Picker
bind = SUPER, P, exec, hyprpicker

#Screenshot
bind = SUPER, S, exec, hyprshot -m region -o ~/Pictures/screenshots/

#Clipboard
bind = SUPER, V, exec, cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy

#Change Focused Window 
bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

#Move to Adjacent Workspace
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2

#Move Window Relative to Current Workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2

#Mouse 
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

#Switch Layouts
bind = SUPER ALT, D, exec, hyprctl keyword general:layout "dwindle"
bind = SUPER ALT, S, exec, hyprctl keyword general:layout "scrolling"

#Audio
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

#Brightness
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

#Player
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
