general {
  gaps_in = 2
  gaps_out = 4
  border_size = 2
  col.active_border = rgb(4BDFB6)
  col.inactive_border = rgb(4B4074)
  resize_on_border = false
  allow_tearing = true
  layout = scrolling
}

decoration {
  rounding = 4
  rounding_power = 2

  active_opacity = 1
  inactive_opacity = 1

  shadow {
    enabled = false
    range = 4
    render_power = 1
    color = rgb(E29074)
  }

  blur {
    enabled = false
    size = 16
    passes = 1
    vibrancy = 0
  }
}

dwindle {
  pseudotile = true 
  preserve_split = true 
}

scrolling {
  fullscreen_on_one_column = true
  focus_fit_method = 1
  column_width = 0.9
  direction = right
}

misc {
  force_default_wallpaper = 1 
  disable_hyprland_logo = true 
  font_family = "JetBrainsMono Nerd Font"
}

render {
  cm_sdr_eotf = 2
}
