input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options = caps:escape 
  kb_rules =
  accel_profile = flat
  follow_mouse = 1

  sensitivity = 0
  touchpad {
    natural_scroll = true
    scroll_factor = 0.5
  }
}

# touchpad settings
device {
  name = pixa3848:00-093a:3848-touchpad
  sensitivity = 0.25
  enabled = 0
}

device {
  name = ergo-m575s-mouse
  sensitivity = 0.5
}

# hyprland exit
# bind = SUPER, Escape, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# plugin binds
# bind = SUPER, Tab, hyprexpo:expo, toggle # Shows All Windows

# config reload
bind = SUPER, R, exec, ~/dotfiles/scripts/reload.sh

# minimal config toggle
bind = SUPER, F1, exec, ~/dotfiles/scripts/gamemode.sh

# basic window management
bind = SHIFT, F11, togglefloating,
bind = , F11, fullscreen,
bind = SUPER, S, layoutmsg, togglesplit
bind = SUPER, Q, killactive,

# window focus
gesture = 3, left, dispatcher, layoutmsg, move +col 
gesture = 3, right, dispatcher, layoutmsg, move -col
bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

# window swap
bind = SUPER SHIFT, H, layoutmsg, swapcol l
bind = SUPER SHIFT, L, layoutmsg, swapcol r

# window move
bindm = SUPER, mouse:272, movewindow
bind = ALT SHIFT, H, moveactive, -90 0
bind = ALT SHIFT, J, moveactive, 0 160 
bind = ALT SHIFT, K, moveactive, 0 -160 
bind = ALT SHIFT, L, moveactive, 90 0

# window resize
bindm = SUPER, mouse:273, resizewindow
bind = SUPER CONTROL, H, layoutmsg, colresize -0.333333
bind = SUPER CONTROL, L, layoutmsg, colresize +0.333333

# workspace switch
bind = SUPER, J, workspace, 1
bind = SUPER, K, workspace, 2
# bind = SUPER, 3, workspace, 3

# window move to workspace
bind = SUPER SHIFT, J, movetoworkspace, 1
bind = SUPER SHIFT, K, movetoworkspace, 2
# bind = SUPER CONTROL, 3, movetoworkspace, 3

# program run
bind = SUPER, T, exec, $terminal
bind = SUPER SHIFT, F23, exec, $terminal
bind = SUPER, E, exec, [float; size 1080 540; move 420 50] $file_manager
bind = SUPER, B, exec, $browser
bind = , XF86Presentation, exec, [float; size 1080 540; move 420 50] $system_monitor
bind = SUPER, Space, exec, $application_launcher
bind = SUPER, C, exec, hyprpicker -a -f hex -n -u 256 -s 10 
bind = , Print, exec, hyprshot -m region -o ~/screenshots/
bind = SUPER, V, exec, cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy 
bind = SUPER, 1, exec, kitty bluetui
bind = SUPER, 2, exec, kitty gazelle
bind = SUPER, 3, exec, kitty wiremix
bind = SUPER, 4, exec, kitty ncdu

# audio controls
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# brightness controls
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

