# generic
monitorv2 {
  output = 
  mode = preferred
  position = -1920x0
  scale = 1
  transform = 0
}

# main
monitorv2 {
  output = eDP-1
  mode = 1920x1080@165
  position = 0x0
  scale = 1
  transform = 0
}

# second
monitorv2 {
  output = HDMI-A-2
  mode = 1920x1080@74.97
  # position = -240x-1440
  position = 0x-1080
  scale = 1
  transform = 0
}

render {
  direct_scanout = 0
}
