# Main Monitor
monitorv2 {
  output = eDP-1
  mode = 1920x1080@165
  position = 0x0
  scale = 1
  transform = 0
}

# Second Monitor
monitor = HDMI-A-2, preferred, 1920x0, 1
# monitorv2 {
#  output = 
#  mode = preferred
#  position = 1920x0
#  scale = 1
#  transform = 0
#}

render {
  direct_scanout = 0
}
