# Ignores Maximize Requests from All Apps
windowrule {
  name = suppress-maximize-events
  match:class = .*
  suppress_event = maximize
}

# Fixes Some Dragging Issues with XWayland
windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false
  no_focus = true
}

# Hyprland-run windowrule
windowrule {
  name = move-hyprland-run
  match:class = hyprland-run
  move = 20 monitor_h-120
  float = yes
}

# Blurs Waybar
layerrule {
  name = blur-waybar
  blur = on
  ignore_alpha = 0.2
  match:namespace = waybar
}

# Blurs SwayNC
layerrule {
  name = blur-swaync
  blur = on
  ignore_alpha = 0.2
  match:namespace = swaync-control-center
}

# Persistent Workspaces
workspace = 1, persistent:true
workspace = 2, persistent:true, layout:dwindle
workspace = 3, persistent:true, layout:dwindle
workspace = 4, persistent:true, layout:dwindle
