# Wallpaper
#exec-once = hyprpaper 
exec-once = swaybg --mode stretch --image ~/Pictures/wallpapers/default.png  

# Top Status Bar
exec-once = waybar 

# Polkit Authentication Daemon
exec-once = systemctl --user start hyprpolkitagent

# Notification Center
exec-once = swaync

# Scheduled Filter
exec-once = hyprsunset

# Auto-mount USB Drives
exec-once = udiskie

#Plugins
# exec-once = hyprpm reload -n

# Clipboard
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
