# wallpaper
# exec-once = hyprpaper 
exec-once = swaybg --mode stretch --image ~/Pictures/wallpapers/default.png  

# top status bar
exec-once = waybar 

# polkit authentication daemon
exec-once = systemctl --user start hyprpolkitagent

# notifications 
exec-once = swaync
# exec-once = dunst

# scheduled blue light filter
exec-once = hyprsunset

# idling actions
exec-once = hypridle

# auto-mount usb drives
exec-once = udiskie

#plugins
# exec-once = hyprpm reload -n

# clipboard
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# makeshift login screen
# exec-once = hyprlock
