# Shell
shell_integration enabled no-cursor

# Window
background_opacity 0.75
dim_opacity 0.75

# Font
font_family JetBrainsMono Nerd Font
font_size 12

# Cursor
cursor #e2dff9
cursor_text_color #000000
cursor_shape block
cursor_blink_interval 0.25
cursor_trail 1
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 0

# Primary colors
foreground #ffffff
background #000000
selection_foreground #000000
selection_background #e2dff9

# Normal colors
color0  #4b4074
color1  #e24074
color2  #4bdf74
color3  #e2df74
color4  #4b40f9
color5  #e240f9
color6  #4bdff9
color7  #e2dff9

# bright colors
color8  #7160ae
color9  #ff60ae
color10 #71ffae
color11 #ffffae
color12 #7160ff
color13 #ff60ff
color14 #71ffff
color15 #ffffff
