"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '$all'

[character]
success_symbol = '[𜰘𜰙](bold #71FFAD)'
error_symbol = '[𜰘𜰚](bold #FF5FAD) '
vimcmd_symbol = '[𜰘𜲂](bold #FFFFAD) '

