"$schema" = 'https://starship.rs/config-schema.json'

 format = '''
$hostname$username$sudo$cmd_duration$battery
$git_branch$git_status$directory
$character'''

[character]
success_symbol = '[-->](bold #71ffae)'
error_symbol = '[~~>](bold #ff60ae)'
vimcmd_symbol = '[>--](bold #ffffae)'
format = '$symbol '

[battery]
full_symbol = '󰁹'
charging_symbol = '󰂏'
discharging_symbol = '󰂌'
unknown_symbol = '󰂑'
empty_symbol = '󰂎'

[directory]
style = 'bold #71ffff'
truncation_length = 99
truncation_symbol = ''
read_only_style = '#e2df74'
read_only = '󰌾'
format = '[$path]($style) [$read_only]($read_only_style) '

[username]
show_always = true
style_user = '#ffb0ae'
style_root = '#ff60d7'
format = '[$user]($style) '

[hostname]
ssh_only = false
style = 'bold #7160ff'
format = '[$ssh_symbol$hostname]($style) '

[shell]
disabled = false
fish_indicator = '󰈺'
zsh_indicator = 'zsh'
bash_indicator = ''
style = 'bold #ffffff'
format = '[$indicator]($style) '

[os]
disabled = false
style = '#71b0ff'
format = '[$symbol]($style) '
[os.symbols]
Arch = '󰣇'
Mint = '󰣭'
Macos = '󰀵'
Linux = '󰌽'
Windows = '󰖳'

[git_branch]
style = 'italic #ffffae'
symbol ='󰘬'
format = '[$symbol $branch(:$remote_branch)]($style) '

[git_status]
style = 'bold #ff60ae'
deleted = 'x'
format ='([\[$all_status$ahead_behind\]]($style)) '
