"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '$all'

[character]
success_symbol = '[-->](bold #71ffae)'
error_symbol = '[~~>](bold #ff60ae)'
vimcmd_symbol = '[>->](bold #ffffae)'

