--require('lua.scripts.background_shuffler')

require('lua.config.environment')
require('lua.config.permissions')
require('lua.config.input')
require('lua.config.layout')
require('lua.config.rules')
require('lua.config.appearance')
require('lua.config.animation')
require('lua.config.monitors')
require('lua.config.startup')
