require('config.environment')
require('config.permissions')
require('config.input')
require('config.layout')
require('config.rules')
require('config.appearance')
require('config.animation')
require('config.monitors')
require('config.run_on_events')

