# Monitors
source = modules/monitors.conf

# Startup
source = modules/startup.conf

# Looks
source = modules/looks.conf

# Animations
source = modules/animations.conf

# Applications
source = modules/applications.conf

# Environment Variables
source = modules/envvars.conf

# Window and Workspace Rules
source = modules/rules.conf

# Input
source = modules/mappings.conf 

# Permissions
source = modules/permissions.conf 

# Plugins
# source = modules/plugins.conf
