general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timout = 0
}

animations {
    enabled = true

    bezier = bounce, 0.5, 1.5, 0.5, -0.5
    bezier = jump, 1, 0, 0, 0
    bezier = linear, 0, 0, 1, 1

    animation = fadeIn, 1, 2.5, jump
    animation = fadeOut, 1, 2.5, jump
    animation = inputFieldDots, 1, 2.5, bounce
}

background {
    monitor =
    path = screenshot
    blur_size = 4
    blur_passes = 2
    noise = 0
    contrast = 1
    brightness = 1
    vibrancy = 0
    vibrancy_darkness = 0
}

input-field {
    monitor =
    size = 100%, 5%

    outline_thickness = 0
    inner_color = rgba(000000bf)

    font_color = rgb(ffffff)
    fade_on_empty = false
    fade_timout = 250
    rounding = 4

    font_family = JetBrainsMono Nerd Font Propo
    placeholder_text = [ PASSWORD ]
    fail_text = [ INCORRECT ]

    check_color = rgba(26703abf)
    fail_color = rgba(71203abf)

    dots_text_format = 󰮔 
    dots_size = 0.5
    dots_spacing = 0.125

    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%I:%M"
    font_size = 32
    font_family = JetBrainsMono Nerd Font Propo

    position = -80, 0
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%m-%d"
    font_size = 32
    font_family = JetBrainsMono Nerd Font Propo

    position = 80, 0
    halign = center
    valign = top
}
