background = 0xBF251F39
font_size = 12
font_family = JetBrains Nerd Font Mono
font_family_monospace = JetBrains Nerd Font Mono
text = 0xFF4BDFB6
bright_text = 0xFF71FFD6
base = 0xFF26203A
alternate_base = 0xBF251F39
accent = 0xFFFF5FAD
accent_secondary = 0xFFFF5FAD
rounding_large = 4
rounding_small = 4
