background = 0xA626203A
font_size = 12
font_family = JetBrains Nerd Font Mono
font_family_monospace = JetBrains Nerd Font Mono
text = 0xFFE2DFF9
bright_text = 0xFF71FFD6
base = 0xA626203A
alternate_base = 0xA626203A
accent = 0xFFE2DFF9
accent_secondary = 0xFFE2DFF9
rounding_large = 8
rounding_small = 8
