# Shell
shell_integration enabled no-cursor

# Window
background_opacity 0.75
dim_opacity 0.5

# Font
font_family JetBrainsMono Nerd Font
font_size 12

# Cursor
cursor_shape block
cursor_blink_interval 0.25
cursor_trail 1
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 0

# Primary colors
foreground #E2DFF9
background #251F39
selection_foreground #251F39
selection_background #E2DFF9

# Normal colors
color0  #4B3F73
color1  #E23F73
color2  #4BDF73
color3  #E2DF73
color4  #4B3FF9
color5  #E23FF9
color6  #4BDFF9
color7  #E2DFF9

# Bright colors
color8  #715FAD
color9  #FF5FAD
color10 #71FFAD
color11 #FFFFAD
color12 #715FFF
color13 #FF5FFF
color14 #71FFFF
color15 #FFFFFF
