vim.cmd("set number relativenumber")
vim.cmd("set expandtab")
vim.cmd("set autoindent")
vim.cmd("set smartindent")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set incsearch")
vim.cmd("set ignorecase")

require("config.lazy")
